// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrdersRepository creates a new instance of MockOrdersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersRepository {
	mock := &MockOrdersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrdersRepository is an autogenerated mock type for the OrdersRepository type
type MockOrdersRepository struct {
	mock.Mock
}

type MockOrdersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersRepository) EXPECT() *MockOrdersRepository_Expecter {
	return &MockOrdersRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) Add(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrdersRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockOrdersRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrdersRepository_Expecter) Add(ctx interface{}, order interface{}) *MockOrdersRepository_Add_Call {
	return &MockOrdersRepository_Add_Call{Call: _e.mock.On("Add", ctx, order)}
}

func (_c *MockOrdersRepository_Add_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrdersRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_Add_Call) Return(err error) *MockOrdersRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrdersRepository_Add_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockOrdersRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) Close() {
	_mock.Called()
	return
}

// MockOrdersRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockOrdersRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockOrdersRepository_Expecter) Close() *MockOrdersRepository_Close_Call {
	return &MockOrdersRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockOrdersRepository_Close_Call) Run(run func()) *MockOrdersRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrdersRepository_Close_Call) Return() *MockOrdersRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrdersRepository_Close_Call) RunAndReturn(run func()) *MockOrdersRepository_Close_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) Get(ctx context.Context, number string) (*model.Order, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrdersRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockOrdersRepository_Expecter) Get(ctx interface{}, number interface{}) *MockOrdersRepository_Get_Call {
	return &MockOrdersRepository_Get_Call{Call: _e.mock.On("Get", ctx, number)}
}

func (_c *MockOrdersRepository_Get_Call) Run(run func(ctx context.Context, number string)) *MockOrdersRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_Get_Call) Return(order *model.Order, err error) *MockOrdersRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrdersRepository_Get_Call) RunAndReturn(run func(ctx context.Context, number string) (*model.Order, error)) *MockOrdersRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockOrdersRepository
func (_mock *MockOrdersRepository) Has(ctx context.Context, number string) (bool, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, number)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrdersRepository_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockOrdersRepository_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockOrdersRepository_Expecter) Has(ctx interface{}, number interface{}) *MockOrdersRepository_Has_Call {
	return &MockOrdersRepository_Has_Call{Call: _e.mock.On("Has", ctx, number)}
}

func (_c *MockOrdersRepository_Has_Call) Run(run func(ctx context.Context, number string)) *MockOrdersRepository_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrdersRepository_Has_Call) Return(b bool, err error) *MockOrdersRepository_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrdersRepository_Has_Call) RunAndReturn(run func(ctx context.Context, number string) (bool, error)) *MockOrdersRepository_Has_Call {
	_c.Call.Return(run)
	return _c
}
