// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRulesRepository creates a new instance of MockRulesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRulesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRulesRepository {
	mock := &MockRulesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRulesRepository is an autogenerated mock type for the RulesRepository type
type MockRulesRepository struct {
	mock.Mock
}

type MockRulesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRulesRepository) EXPECT() *MockRulesRepository_Expecter {
	return &MockRulesRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) Add(ctx context.Context, rule *model.RewardRule) error {
	ret := _mock.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RewardRule) error); ok {
		r0 = returnFunc(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRulesRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRulesRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *model.RewardRule
func (_e *MockRulesRepository_Expecter) Add(ctx interface{}, rule interface{}) *MockRulesRepository_Add_Call {
	return &MockRulesRepository_Add_Call{Call: _e.mock.On("Add", ctx, rule)}
}

func (_c *MockRulesRepository_Add_Call) Run(run func(ctx context.Context, rule *model.RewardRule)) *MockRulesRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RewardRule
		if args[1] != nil {
			arg1 = args[1].(*model.RewardRule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRulesRepository_Add_Call) Return(err error) *MockRulesRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRulesRepository_Add_Call) RunAndReturn(run func(ctx context.Context, rule *model.RewardRule) error) *MockRulesRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) All(ctx context.Context) ([]model.RewardRule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []model.RewardRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.RewardRule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.RewardRule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RewardRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesRepository_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockRulesRepository_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRulesRepository_Expecter) All(ctx interface{}) *MockRulesRepository_All_Call {
	return &MockRulesRepository_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockRulesRepository_All_Call) Run(run func(ctx context.Context)) *MockRulesRepository_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRulesRepository_All_Call) Return(rewardRules []model.RewardRule, err error) *MockRulesRepository_All_Call {
	_c.Call.Return(rewardRules, err)
	return _c
}

func (_c *MockRulesRepository_All_Call) RunAndReturn(run func(ctx context.Context) ([]model.RewardRule, error)) *MockRulesRepository_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) Close() {
	_mock.Called()
	return
}

// MockRulesRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRulesRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRulesRepository_Expecter) Close() *MockRulesRepository_Close_Call {
	return &MockRulesRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRulesRepository_Close_Call) Run(run func()) *MockRulesRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRulesRepository_Close_Call) Return() *MockRulesRepository_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRulesRepository_Close_Call) RunAndReturn(run func()) *MockRulesRepository_Close_Call {
	_c.Run(run)
	return _c
}

// Has provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) Has(ctx context.Context, match string) (bool, error) {
	ret := _mock.Called(ctx, match)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, match)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, match)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, match)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesRepository_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockRulesRepository_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - match string
func (_e *MockRulesRepository_Expecter) Has(ctx interface{}, match interface{}) *MockRulesRepository_Has_Call {
	return &MockRulesRepository_Has_Call{Call: _e.mock.On("Has", ctx, match)}
}

func (_c *MockRulesRepository_Has_Call) Run(run func(ctx context.Context, match string)) *MockRulesRepository_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRulesRepository_Has_Call) Return(b bool, err error) *MockRulesRepository_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRulesRepository_Has_Call) RunAndReturn(run func(ctx context.Context, match string) (bool, error)) *MockRulesRepository_Has_Call {
	_c.Call.Return(run)
	return _c
}
