// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRegisterer creates a new instance of MockUserRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRegisterer {
	mock := &MockUserRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRegisterer is an autogenerated mock type for the UserRegisterer type
type MockUserRegisterer struct {
	mock.Mock
}

type MockUserRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRegisterer) EXPECT() *MockUserRegisterer_Expecter {
	return &MockUserRegisterer_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockUserRegisterer
func (_mock *MockUserRegisterer) Register(ctx context.Context, login string, password string) (*models.User, string, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, string, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, login, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRegisterer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserRegisterer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockUserRegisterer_Expecter) Register(ctx interface{}, login interface{}, password interface{}) *MockUserRegisterer_Register_Call {
	return &MockUserRegisterer_Register_Call{Call: _e.mock.On("Register", ctx, login, password)}
}

func (_c *MockUserRegisterer_Register_Call) Run(run func(ctx context.Context, login string, password string)) *MockUserRegisterer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRegisterer_Register_Call) Return(user *models.User, s string, err error) *MockUserRegisterer_Register_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *MockUserRegisterer_Register_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (*models.User, string, error)) *MockUserRegisterer_Register_Call {
	_c.Call.Return(run)
	return _c
}
