// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockAccrual creates a new instance of MockAccrual. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrual(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrual {
	mock := &MockAccrual{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrual is an autogenerated mock type for the Accrual type
type MockAccrual struct {
	mock.Mock
}

type MockAccrual_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrual) EXPECT() *MockAccrual_Expecter {
	return &MockAccrual_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockAccrual
func (_mock *MockAccrual) Get(ctx context.Context, order models.OrderProcess) (*models.AccrualResponse, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.AccrualResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrderProcess) (*models.AccrualResponse, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrderProcess) *models.AccrualResponse); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccrualResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.OrderProcess) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrual_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccrual_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.OrderProcess
func (_e *MockAccrual_Expecter) Get(ctx interface{}, order interface{}) *MockAccrual_Get_Call {
	return &MockAccrual_Get_Call{Call: _e.mock.On("Get", ctx, order)}
}

func (_c *MockAccrual_Get_Call) Run(run func(ctx context.Context, order models.OrderProcess)) *MockAccrual_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.OrderProcess
		if args[1] != nil {
			arg1 = args[1].(models.OrderProcess)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrual_Get_Call) Return(accrualResponse *models.AccrualResponse, err error) *MockAccrual_Get_Call {
	_c.Call.Return(accrualResponse, err)
	return _c
}

func (_c *MockAccrual_Get_Call) RunAndReturn(run func(ctx context.Context, order models.OrderProcess) (*models.AccrualResponse, error)) *MockAccrual_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetryAfter provides a mock function for the type MockAccrual
func (_mock *MockAccrual) GetRetryAfter() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRetryAfter")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockAccrual_GetRetryAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetryAfter'
type MockAccrual_GetRetryAfter_Call struct {
	*mock.Call
}

// GetRetryAfter is a helper method to define mock.On call
func (_e *MockAccrual_Expecter) GetRetryAfter() *MockAccrual_GetRetryAfter_Call {
	return &MockAccrual_GetRetryAfter_Call{Call: _e.mock.On("GetRetryAfter")}
}

func (_c *MockAccrual_GetRetryAfter_Call) Run(run func()) *MockAccrual_GetRetryAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccrual_GetRetryAfter_Call) Return(duration time.Duration) *MockAccrual_GetRetryAfter_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockAccrual_GetRetryAfter_Call) RunAndReturn(run func() time.Duration) *MockAccrual_GetRetryAfter_Call {
	_c.Call.Return(run)
	return _c
}

// SetRetryAfter provides a mock function for the type MockAccrual
func (_mock *MockAccrual) SetRetryAfter(t time.Duration) {
	_mock.Called(t)
	return
}

// MockAccrual_SetRetryAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRetryAfter'
type MockAccrual_SetRetryAfter_Call struct {
	*mock.Call
}

// SetRetryAfter is a helper method to define mock.On call
//   - t time.Duration
func (_e *MockAccrual_Expecter) SetRetryAfter(t interface{}) *MockAccrual_SetRetryAfter_Call {
	return &MockAccrual_SetRetryAfter_Call{Call: _e.mock.On("SetRetryAfter", t)}
}

func (_c *MockAccrual_SetRetryAfter_Call) Run(run func(t time.Duration)) *MockAccrual_SetRetryAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccrual_SetRetryAfter_Call) Return() *MockAccrual_SetRetryAfter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAccrual_SetRetryAfter_Call) RunAndReturn(run func(t time.Duration)) *MockAccrual_SetRetryAfter_Call {
	_c.Run(run)
	return _c
}
