// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRuleRegisterer creates a new instance of MockRuleRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuleRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuleRegisterer {
	mock := &MockRuleRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuleRegisterer is an autogenerated mock type for the RuleRegisterer type
type MockRuleRegisterer struct {
	mock.Mock
}

type MockRuleRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuleRegisterer) EXPECT() *MockRuleRegisterer_Expecter {
	return &MockRuleRegisterer_Expecter{mock: &_m.Mock}
}

// RegisterRule provides a mock function for the type MockRuleRegisterer
func (_mock *MockRuleRegisterer) RegisterRule(ctx context.Context, rule *model.RewardRule) error {
	ret := _mock.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RewardRule) error); ok {
		r0 = returnFunc(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRuleRegisterer_RegisterRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRule'
type MockRuleRegisterer_RegisterRule_Call struct {
	*mock.Call
}

// RegisterRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *model.RewardRule
func (_e *MockRuleRegisterer_Expecter) RegisterRule(ctx interface{}, rule interface{}) *MockRuleRegisterer_RegisterRule_Call {
	return &MockRuleRegisterer_RegisterRule_Call{Call: _e.mock.On("RegisterRule", ctx, rule)}
}

func (_c *MockRuleRegisterer_RegisterRule_Call) Run(run func(ctx context.Context, rule *model.RewardRule)) *MockRuleRegisterer_RegisterRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RewardRule
		if args[1] != nil {
			arg1 = args[1].(*model.RewardRule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleRegisterer_RegisterRule_Call) Return(err error) *MockRuleRegisterer_RegisterRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRuleRegisterer_RegisterRule_Call) RunAndReturn(run func(ctx context.Context, rule *model.RewardRule) error) *MockRuleRegisterer_RegisterRule_Call {
	_c.Call.Return(run)
	return _c
}
