// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderInformer creates a new instance of MockOrderInformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderInformer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderInformer {
	mock := &MockOrderInformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderInformer is an autogenerated mock type for the OrderInformer type
type MockOrderInformer struct {
	mock.Mock
}

type MockOrderInformer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderInformer) EXPECT() *MockOrderInformer_Expecter {
	return &MockOrderInformer_Expecter{mock: &_m.Mock}
}

// InformOrder provides a mock function for the type MockOrderInformer
func (_mock *MockOrderInformer) InformOrder(ctx context.Context, number string) (*model.Order, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for InformOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderInformer_InformOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InformOrder'
type MockOrderInformer_InformOrder_Call struct {
	*mock.Call
}

// InformOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockOrderInformer_Expecter) InformOrder(ctx interface{}, number interface{}) *MockOrderInformer_InformOrder_Call {
	return &MockOrderInformer_InformOrder_Call{Call: _e.mock.On("InformOrder", ctx, number)}
}

func (_c *MockOrderInformer_InformOrder_Call) Run(run func(ctx context.Context, number string)) *MockOrderInformer_InformOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderInformer_InformOrder_Call) Return(order *model.Order, err error) *MockOrderInformer_InformOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderInformer_InformOrder_Call) RunAndReturn(run func(ctx context.Context, number string) (*model.Order, error)) *MockOrderInformer_InformOrder_Call {
	_c.Call.Return(run)
	return _c
}
