// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRegisterer creates a new instance of MockOrderRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRegisterer {
	mock := &MockOrderRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRegisterer is an autogenerated mock type for the OrderRegisterer type
type MockOrderRegisterer struct {
	mock.Mock
}

type MockOrderRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRegisterer) EXPECT() *MockOrderRegisterer_Expecter {
	return &MockOrderRegisterer_Expecter{mock: &_m.Mock}
}

// RegisterOrder provides a mock function for the type MockOrderRegisterer
func (_mock *MockOrderRegisterer) RegisterOrder(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRegisterer_RegisterOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterOrder'
type MockOrderRegisterer_RegisterOrder_Call struct {
	*mock.Call
}

// RegisterOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrderRegisterer_Expecter) RegisterOrder(ctx interface{}, order interface{}) *MockOrderRegisterer_RegisterOrder_Call {
	return &MockOrderRegisterer_RegisterOrder_Call{Call: _e.mock.On("RegisterOrder", ctx, order)}
}

func (_c *MockOrderRegisterer_RegisterOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrderRegisterer_RegisterOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRegisterer_RegisterOrder_Call) Return(err error) *MockOrderRegisterer_RegisterOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRegisterer_RegisterOrder_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockOrderRegisterer_RegisterOrder_Call {
	_c.Call.Return(run)
	return _c
}
