// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGophermart creates a new instance of MockGophermart. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGophermart(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGophermart {
	mock := &MockGophermart{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGophermart is an autogenerated mock type for the Gophermart type
type MockGophermart struct {
	mock.Mock
}

type MockGophermart_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGophermart) EXPECT() *MockGophermart_Expecter {
	return &MockGophermart_Expecter{mock: &_m.Mock}
}

// CountWithdrawal provides a mock function for the type MockGophermart
func (_mock *MockGophermart) CountWithdrawal(ctx context.Context, indexWithdrawal models.IndexWithdrawal) (int64, error) {
	ret := _mock.Called(ctx, indexWithdrawal)

	if len(ret) == 0 {
		panic("no return value specified for CountWithdrawal")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) (int64, error)); ok {
		return returnFunc(ctx, indexWithdrawal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) int64); ok {
		r0 = returnFunc(ctx, indexWithdrawal)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexWithdrawal) error); ok {
		r1 = returnFunc(ctx, indexWithdrawal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGophermart_CountWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountWithdrawal'
type MockGophermart_CountWithdrawal_Call struct {
	*mock.Call
}

// CountWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - indexWithdrawal models.IndexWithdrawal
func (_e *MockGophermart_Expecter) CountWithdrawal(ctx interface{}, indexWithdrawal interface{}) *MockGophermart_CountWithdrawal_Call {
	return &MockGophermart_CountWithdrawal_Call{Call: _e.mock.On("CountWithdrawal", ctx, indexWithdrawal)}
}

func (_c *MockGophermart_CountWithdrawal_Call) Run(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal)) *MockGophermart_CountWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexWithdrawal
		if args[1] != nil {
			arg1 = args[1].(models.IndexWithdrawal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_CountWithdrawal_Call) Return(n int64, err error) *MockGophermart_CountWithdrawal_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGophermart_CountWithdrawal_Call) RunAndReturn(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal) (int64, error)) *MockGophermart_CountWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// IndexWithdrawal provides a mock function for the type MockGophermart
func (_mock *MockGophermart) IndexWithdrawal(ctx context.Context, indexWithdrawal models.IndexWithdrawal) ([]models.IndexWithdrawalResponse, error) {
	ret := _mock.Called(ctx, indexWithdrawal)

	if len(ret) == 0 {
		panic("no return value specified for IndexWithdrawal")
	}

	var r0 []models.IndexWithdrawalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) ([]models.IndexWithdrawalResponse, error)); ok {
		return returnFunc(ctx, indexWithdrawal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) []models.IndexWithdrawalResponse); ok {
		r0 = returnFunc(ctx, indexWithdrawal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IndexWithdrawalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexWithdrawal) error); ok {
		r1 = returnFunc(ctx, indexWithdrawal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGophermart_IndexWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexWithdrawal'
type MockGophermart_IndexWithdrawal_Call struct {
	*mock.Call
}

// IndexWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - indexWithdrawal models.IndexWithdrawal
func (_e *MockGophermart_Expecter) IndexWithdrawal(ctx interface{}, indexWithdrawal interface{}) *MockGophermart_IndexWithdrawal_Call {
	return &MockGophermart_IndexWithdrawal_Call{Call: _e.mock.On("IndexWithdrawal", ctx, indexWithdrawal)}
}

func (_c *MockGophermart_IndexWithdrawal_Call) Run(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal)) *MockGophermart_IndexWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexWithdrawal
		if args[1] != nil {
			arg1 = args[1].(models.IndexWithdrawal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_IndexWithdrawal_Call) Return(indexWithdrawalResponses []models.IndexWithdrawalResponse, err error) *MockGophermart_IndexWithdrawal_Call {
	_c.Call.Return(indexWithdrawalResponses, err)
	return _c
}

func (_c *MockGophermart_IndexWithdrawal_Call) RunAndReturn(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal) ([]models.IndexWithdrawalResponse, error)) *MockGophermart_IndexWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// StoreWithdrawal provides a mock function for the type MockGophermart
func (_mock *MockGophermart) StoreWithdrawal(ctx context.Context, storeWithdrawal models.StoreWithdrawal, setDefaultBalance models.SetDefaultBalanceRequest) error {
	ret := _mock.Called(ctx, storeWithdrawal, setDefaultBalance)

	if len(ret) == 0 {
		panic("no return value specified for StoreWithdrawal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreWithdrawal, models.SetDefaultBalanceRequest) error); ok {
		r0 = returnFunc(ctx, storeWithdrawal, setDefaultBalance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGophermart_StoreWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreWithdrawal'
type MockGophermart_StoreWithdrawal_Call struct {
	*mock.Call
}

// StoreWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - storeWithdrawal models.StoreWithdrawal
//   - setDefaultBalance models.SetDefaultBalanceRequest
func (_e *MockGophermart_Expecter) StoreWithdrawal(ctx interface{}, storeWithdrawal interface{}, setDefaultBalance interface{}) *MockGophermart_StoreWithdrawal_Call {
	return &MockGophermart_StoreWithdrawal_Call{Call: _e.mock.On("StoreWithdrawal", ctx, storeWithdrawal, setDefaultBalance)}
}

func (_c *MockGophermart_StoreWithdrawal_Call) Run(run func(ctx context.Context, storeWithdrawal models.StoreWithdrawal, setDefaultBalance models.SetDefaultBalanceRequest)) *MockGophermart_StoreWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreWithdrawal
		if args[1] != nil {
			arg1 = args[1].(models.StoreWithdrawal)
		}
		var arg2 models.SetDefaultBalanceRequest
		if args[2] != nil {
			arg2 = args[2].(models.SetDefaultBalanceRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGophermart_StoreWithdrawal_Call) Return(err error) *MockGophermart_StoreWithdrawal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGophermart_StoreWithdrawal_Call) RunAndReturn(run func(ctx context.Context, storeWithdrawal models.StoreWithdrawal, setDefaultBalance models.SetDefaultBalanceRequest) error) *MockGophermart_StoreWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}
