// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthTokenProvider creates a new instance of MockAuthTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenProvider {
	mock := &MockAuthTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthTokenProvider is an autogenerated mock type for the AuthTokenProvider type
type MockAuthTokenProvider struct {
	mock.Mock
}

type MockAuthTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenProvider) EXPECT() *MockAuthTokenProvider_Expecter {
	return &MockAuthTokenProvider_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockAuthTokenProvider
func (_mock *MockAuthTokenProvider) Generate(userID models.UserID) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.UserID) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(models.UserID) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(models.UserID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenProvider_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockAuthTokenProvider_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID models.UserID
func (_e *MockAuthTokenProvider_Expecter) Generate(userID interface{}) *MockAuthTokenProvider_Generate_Call {
	return &MockAuthTokenProvider_Generate_Call{Call: _e.mock.On("Generate", userID)}
}

func (_c *MockAuthTokenProvider_Generate_Call) Run(run func(userID models.UserID)) *MockAuthTokenProvider_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UserID
		if args[0] != nil {
			arg0 = args[0].(models.UserID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthTokenProvider_Generate_Call) Return(s string, err error) *MockAuthTokenProvider_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthTokenProvider_Generate_Call) RunAndReturn(run func(userID models.UserID) (string, error)) *MockAuthTokenProvider_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockAuthTokenProvider
func (_mock *MockAuthTokenProvider) Parse(tokenString string) (models.UserID, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 models.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.UserID, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.UserID); ok {
		r0 = returnFunc(tokenString)
	} else {
		r0 = ret.Get(0).(models.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenProvider_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockAuthTokenProvider_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenString string
func (_e *MockAuthTokenProvider_Expecter) Parse(tokenString interface{}) *MockAuthTokenProvider_Parse_Call {
	return &MockAuthTokenProvider_Parse_Call{Call: _e.mock.On("Parse", tokenString)}
}

func (_c *MockAuthTokenProvider_Parse_Call) Run(run func(tokenString string)) *MockAuthTokenProvider_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthTokenProvider_Parse_Call) Return(userID models.UserID, err error) *MockAuthTokenProvider_Parse_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockAuthTokenProvider_Parse_Call) RunAndReturn(run func(tokenString string) (models.UserID, error)) *MockAuthTokenProvider_Parse_Call {
	_c.Call.Return(run)
	return _c
}
