// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGophermart creates a new instance of MockGophermart. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGophermart(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGophermart {
	mock := &MockGophermart{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGophermart is an autogenerated mock type for the Gophermart type
type MockGophermart struct {
	mock.Mock
}

type MockGophermart_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGophermart) EXPECT() *MockGophermart_Expecter {
	return &MockGophermart_Expecter{mock: &_m.Mock}
}

// CreateDefaultBalance provides a mock function for the type MockGophermart
func (_mock *MockGophermart) CreateDefaultBalance(ctx context.Context, setDefaultBalance models.SetDefaultBalanceRequest) error {
	ret := _mock.Called(ctx, setDefaultBalance)

	if len(ret) == 0 {
		panic("no return value specified for CreateDefaultBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SetDefaultBalanceRequest) error); ok {
		r0 = returnFunc(ctx, setDefaultBalance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGophermart_CreateDefaultBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDefaultBalance'
type MockGophermart_CreateDefaultBalance_Call struct {
	*mock.Call
}

// CreateDefaultBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - setDefaultBalance models.SetDefaultBalanceRequest
func (_e *MockGophermart_Expecter) CreateDefaultBalance(ctx interface{}, setDefaultBalance interface{}) *MockGophermart_CreateDefaultBalance_Call {
	return &MockGophermart_CreateDefaultBalance_Call{Call: _e.mock.On("CreateDefaultBalance", ctx, setDefaultBalance)}
}

func (_c *MockGophermart_CreateDefaultBalance_Call) Run(run func(ctx context.Context, setDefaultBalance models.SetDefaultBalanceRequest)) *MockGophermart_CreateDefaultBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SetDefaultBalanceRequest
		if args[1] != nil {
			arg1 = args[1].(models.SetDefaultBalanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_CreateDefaultBalance_Call) Return(err error) *MockGophermart_CreateDefaultBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGophermart_CreateDefaultBalance_Call) RunAndReturn(run func(ctx context.Context, setDefaultBalance models.SetDefaultBalanceRequest) error) *MockGophermart_CreateDefaultBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockGophermart
func (_mock *MockGophermart) GetBalance(ctx context.Context, getBalance models.GetBalanceRequest) (*models.ShowBalanceResponse, error) {
	ret := _mock.Called(ctx, getBalance)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *models.ShowBalanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetBalanceRequest) (*models.ShowBalanceResponse, error)); ok {
		return returnFunc(ctx, getBalance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetBalanceRequest) *models.ShowBalanceResponse); ok {
		r0 = returnFunc(ctx, getBalance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ShowBalanceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetBalanceRequest) error); ok {
		r1 = returnFunc(ctx, getBalance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGophermart_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockGophermart_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - getBalance models.GetBalanceRequest
func (_e *MockGophermart_Expecter) GetBalance(ctx interface{}, getBalance interface{}) *MockGophermart_GetBalance_Call {
	return &MockGophermart_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, getBalance)}
}

func (_c *MockGophermart_GetBalance_Call) Run(run func(ctx context.Context, getBalance models.GetBalanceRequest)) *MockGophermart_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetBalanceRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetBalanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_GetBalance_Call) Return(showBalanceResponse *models.ShowBalanceResponse, err error) *MockGophermart_GetBalance_Call {
	_c.Call.Return(showBalanceResponse, err)
	return _c
}

func (_c *MockGophermart_GetBalance_Call) RunAndReturn(run func(ctx context.Context, getBalance models.GetBalanceRequest) (*models.ShowBalanceResponse, error)) *MockGophermart_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}
