// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUserValidator creates a new instance of MockAuthUserValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUserValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUserValidator {
	mock := &MockAuthUserValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUserValidator is an autogenerated mock type for the AuthUserValidator type
type MockAuthUserValidator struct {
	mock.Mock
}

type MockAuthUserValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUserValidator) EXPECT() *MockAuthUserValidator_Expecter {
	return &MockAuthUserValidator_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function for the type MockAuthUserValidator
func (_mock *MockAuthUserValidator) ValidateToken(token string) (models.UserID, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 models.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.UserID, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.UserID); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(models.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUserValidator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthUserValidator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockAuthUserValidator_Expecter) ValidateToken(token interface{}) *MockAuthUserValidator_ValidateToken_Call {
	return &MockAuthUserValidator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockAuthUserValidator_ValidateToken_Call) Run(run func(token string)) *MockAuthUserValidator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUserValidator_ValidateToken_Call) Return(userID models.UserID, err error) *MockAuthUserValidator_ValidateToken_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockAuthUserValidator_ValidateToken_Call) RunAndReturn(run func(token string) (models.UserID, error)) *MockAuthUserValidator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function for the type MockAuthUserValidator
func (_mock *MockAuthUserValidator) ValidateUser(ctx context.Context, userID models.UserID) (*models.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserID) (*models.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserID) *models.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUserValidator_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type MockAuthUserValidator_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID models.UserID
func (_e *MockAuthUserValidator_Expecter) ValidateUser(ctx interface{}, userID interface{}) *MockAuthUserValidator_ValidateUser_Call {
	return &MockAuthUserValidator_ValidateUser_Call{Call: _e.mock.On("ValidateUser", ctx, userID)}
}

func (_c *MockAuthUserValidator_ValidateUser_Call) Run(run func(ctx context.Context, userID models.UserID)) *MockAuthUserValidator_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UserID
		if args[1] != nil {
			arg1 = args[1].(models.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUserValidator_ValidateUser_Call) Return(user *models.User, err error) *MockAuthUserValidator_ValidateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthUserValidator_ValidateUser_Call) RunAndReturn(run func(ctx context.Context, userID models.UserID) (*models.User, error)) *MockAuthUserValidator_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}
