// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRulesProvider creates a new instance of MockRulesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRulesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRulesProvider {
	mock := &MockRulesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRulesProvider is an autogenerated mock type for the RulesProvider type
type MockRulesProvider struct {
	mock.Mock
}

type MockRulesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRulesProvider) EXPECT() *MockRulesProvider_Expecter {
	return &MockRulesProvider_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockRulesProvider
func (_mock *MockRulesProvider) All(ctx context.Context) ([]model.RewardRule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []model.RewardRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.RewardRule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.RewardRule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RewardRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesProvider_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockRulesProvider_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRulesProvider_Expecter) All(ctx interface{}) *MockRulesProvider_All_Call {
	return &MockRulesProvider_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockRulesProvider_All_Call) Run(run func(ctx context.Context)) *MockRulesProvider_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRulesProvider_All_Call) Return(rewardRules []model.RewardRule, err error) *MockRulesProvider_All_Call {
	_c.Call.Return(rewardRules, err)
	return _c
}

func (_c *MockRulesProvider_All_Call) RunAndReturn(run func(ctx context.Context) ([]model.RewardRule, error)) *MockRulesProvider_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockRulesProvider
func (_mock *MockRulesProvider) Close() {
	_mock.Called()
	return
}

// MockRulesProvider_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRulesProvider_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRulesProvider_Expecter) Close() *MockRulesProvider_Close_Call {
	return &MockRulesProvider_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRulesProvider_Close_Call) Run(run func()) *MockRulesProvider_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRulesProvider_Close_Call) Return() *MockRulesProvider_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRulesProvider_Close_Call) RunAndReturn(run func()) *MockRulesProvider_Close_Call {
	_c.Run(run)
	return _c
}

// MarkDirty provides a mock function for the type MockRulesProvider
func (_mock *MockRulesProvider) MarkDirty() {
	_mock.Called()
	return
}

// MockRulesProvider_MarkDirty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDirty'
type MockRulesProvider_MarkDirty_Call struct {
	*mock.Call
}

// MarkDirty is a helper method to define mock.On call
func (_e *MockRulesProvider_Expecter) MarkDirty() *MockRulesProvider_MarkDirty_Call {
	return &MockRulesProvider_MarkDirty_Call{Call: _e.mock.On("MarkDirty")}
}

func (_c *MockRulesProvider_MarkDirty_Call) Run(run func()) *MockRulesProvider_MarkDirty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRulesProvider_MarkDirty_Call) Return() *MockRulesProvider_MarkDirty_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRulesProvider_MarkDirty_Call) RunAndReturn(run func()) *MockRulesProvider_MarkDirty_Call {
	_c.Run(run)
	return _c
}
