// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockProcessOrdersRepository creates a new instance of MockProcessOrdersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessOrdersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessOrdersRepository {
	mock := &MockProcessOrdersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessOrdersRepository is an autogenerated mock type for the ProcessOrdersRepository type
type MockProcessOrdersRepository struct {
	mock.Mock
}

type MockProcessOrdersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessOrdersRepository) EXPECT() *MockProcessOrdersRepository_Expecter {
	return &MockProcessOrdersRepository_Expecter{mock: &_m.Mock}
}

// GetBatchForProcessing provides a mock function for the type MockProcessOrdersRepository
func (_mock *MockProcessOrdersRepository) GetBatchForProcessing(ctx context.Context, batchSize int) ([]model.Order, error) {
	ret := _mock.Called(ctx, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchForProcessing")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.Order, error)); ok {
		return returnFunc(ctx, batchSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.Order); ok {
		r0 = returnFunc(ctx, batchSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, batchSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessOrdersRepository_GetBatchForProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchForProcessing'
type MockProcessOrdersRepository_GetBatchForProcessing_Call struct {
	*mock.Call
}

// GetBatchForProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
func (_e *MockProcessOrdersRepository_Expecter) GetBatchForProcessing(ctx interface{}, batchSize interface{}) *MockProcessOrdersRepository_GetBatchForProcessing_Call {
	return &MockProcessOrdersRepository_GetBatchForProcessing_Call{Call: _e.mock.On("GetBatchForProcessing", ctx, batchSize)}
}

func (_c *MockProcessOrdersRepository_GetBatchForProcessing_Call) Run(run func(ctx context.Context, batchSize int)) *MockProcessOrdersRepository_GetBatchForProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProcessOrdersRepository_GetBatchForProcessing_Call) Return(orders []model.Order, err error) *MockProcessOrdersRepository_GetBatchForProcessing_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockProcessOrdersRepository_GetBatchForProcessing_Call) RunAndReturn(run func(ctx context.Context, batchSize int) ([]model.Order, error)) *MockProcessOrdersRepository_GetBatchForProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// ResetStuckOrders provides a mock function for the type MockProcessOrdersRepository
func (_mock *MockProcessOrdersRepository) ResetStuckOrders(ctx context.Context, timeout time.Duration, batchLimit int) (int, error) {
	ret := _mock.Called(ctx, timeout, batchLimit)

	if len(ret) == 0 {
		panic("no return value specified for ResetStuckOrders")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (int, error)); ok {
		return returnFunc(ctx, timeout, batchLimit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) int); ok {
		r0 = returnFunc(ctx, timeout, batchLimit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, timeout, batchLimit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessOrdersRepository_ResetStuckOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetStuckOrders'
type MockProcessOrdersRepository_ResetStuckOrders_Call struct {
	*mock.Call
}

// ResetStuckOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
//   - batchLimit int
func (_e *MockProcessOrdersRepository_Expecter) ResetStuckOrders(ctx interface{}, timeout interface{}, batchLimit interface{}) *MockProcessOrdersRepository_ResetStuckOrders_Call {
	return &MockProcessOrdersRepository_ResetStuckOrders_Call{Call: _e.mock.On("ResetStuckOrders", ctx, timeout, batchLimit)}
}

func (_c *MockProcessOrdersRepository_ResetStuckOrders_Call) Run(run func(ctx context.Context, timeout time.Duration, batchLimit int)) *MockProcessOrdersRepository_ResetStuckOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcessOrdersRepository_ResetStuckOrders_Call) Return(n int, err error) *MockProcessOrdersRepository_ResetStuckOrders_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProcessOrdersRepository_ResetStuckOrders_Call) RunAndReturn(run func(ctx context.Context, timeout time.Duration, batchLimit int) (int, error)) *MockProcessOrdersRepository_ResetStuckOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockProcessOrdersRepository
func (_mock *MockProcessOrdersRepository) UpdateStatus(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessOrdersRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockProcessOrdersRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockProcessOrdersRepository_Expecter) UpdateStatus(ctx interface{}, order interface{}) *MockProcessOrdersRepository_UpdateStatus_Call {
	return &MockProcessOrdersRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, order)}
}

func (_c *MockProcessOrdersRepository_UpdateStatus_Call) Run(run func(ctx context.Context, order *model.Order)) *MockProcessOrdersRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProcessOrdersRepository_UpdateStatus_Call) Return(err error) *MockProcessOrdersRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessOrdersRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *MockProcessOrdersRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
