// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alex-storchak/go-musthave-group-diploma/internal/accrual/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderProcessor creates a new instance of MockOrderProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderProcessor {
	mock := &MockOrderProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderProcessor is an autogenerated mock type for the OrderProcessor type
type MockOrderProcessor struct {
	mock.Mock
}

type MockOrderProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderProcessor) EXPECT() *MockOrderProcessor_Expecter {
	return &MockOrderProcessor_Expecter{mock: &_m.Mock}
}

// ProcessOrder provides a mock function for the type MockOrderProcessor
func (_mock *MockOrderProcessor) ProcessOrder(order *model.Order, rules []model.RewardRule) {
	_mock.Called(order, rules)
	return
}

// MockOrderProcessor_ProcessOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessOrder'
type MockOrderProcessor_ProcessOrder_Call struct {
	*mock.Call
}

// ProcessOrder is a helper method to define mock.On call
//   - order *model.Order
//   - rules []model.RewardRule
func (_e *MockOrderProcessor_Expecter) ProcessOrder(order interface{}, rules interface{}) *MockOrderProcessor_ProcessOrder_Call {
	return &MockOrderProcessor_ProcessOrder_Call{Call: _e.mock.On("ProcessOrder", order, rules)}
}

func (_c *MockOrderProcessor_ProcessOrder_Call) Run(run func(order *model.Order, rules []model.RewardRule)) *MockOrderProcessor_ProcessOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Order
		if args[0] != nil {
			arg0 = args[0].(*model.Order)
		}
		var arg1 []model.RewardRule
		if args[1] != nil {
			arg1 = args[1].([]model.RewardRule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderProcessor_ProcessOrder_Call) Return() *MockOrderProcessor_ProcessOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderProcessor_ProcessOrder_Call) RunAndReturn(run func(order *model.Order, rules []model.RewardRule)) *MockOrderProcessor_ProcessOrder_Call {
	_c.Run(run)
	return _c
}
