// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGophermart creates a new instance of MockGophermart. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGophermart(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGophermart {
	mock := &MockGophermart{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGophermart is an autogenerated mock type for the Gophermart type
type MockGophermart struct {
	mock.Mock
}

type MockGophermart_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGophermart) EXPECT() *MockGophermart_Expecter {
	return &MockGophermart_Expecter{mock: &_m.Mock}
}

// CountOrder provides a mock function for the type MockGophermart
func (_mock *MockGophermart) CountOrder(ctx context.Context, indexOrder models.IndexOrder) (int64, error) {
	ret := _mock.Called(ctx, indexOrder)

	if len(ret) == 0 {
		panic("no return value specified for CountOrder")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) (int64, error)); ok {
		return returnFunc(ctx, indexOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) int64); ok {
		r0 = returnFunc(ctx, indexOrder)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexOrder) error); ok {
		r1 = returnFunc(ctx, indexOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGophermart_CountOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOrder'
type MockGophermart_CountOrder_Call struct {
	*mock.Call
}

// CountOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - indexOrder models.IndexOrder
func (_e *MockGophermart_Expecter) CountOrder(ctx interface{}, indexOrder interface{}) *MockGophermart_CountOrder_Call {
	return &MockGophermart_CountOrder_Call{Call: _e.mock.On("CountOrder", ctx, indexOrder)}
}

func (_c *MockGophermart_CountOrder_Call) Run(run func(ctx context.Context, indexOrder models.IndexOrder)) *MockGophermart_CountOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexOrder
		if args[1] != nil {
			arg1 = args[1].(models.IndexOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_CountOrder_Call) Return(n int64, err error) *MockGophermart_CountOrder_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGophermart_CountOrder_Call) RunAndReturn(run func(ctx context.Context, indexOrder models.IndexOrder) (int64, error)) *MockGophermart_CountOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockGophermart
func (_mock *MockGophermart) GetOrder(ctx context.Context, getOrder models.GetOrder) (*models.Order, error) {
	ret := _mock.Called(ctx, getOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetOrder) (*models.Order, error)); ok {
		return returnFunc(ctx, getOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetOrder) *models.Order); ok {
		r0 = returnFunc(ctx, getOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetOrder) error); ok {
		r1 = returnFunc(ctx, getOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGophermart_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockGophermart_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - getOrder models.GetOrder
func (_e *MockGophermart_Expecter) GetOrder(ctx interface{}, getOrder interface{}) *MockGophermart_GetOrder_Call {
	return &MockGophermart_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, getOrder)}
}

func (_c *MockGophermart_GetOrder_Call) Run(run func(ctx context.Context, getOrder models.GetOrder)) *MockGophermart_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetOrder
		if args[1] != nil {
			arg1 = args[1].(models.GetOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_GetOrder_Call) Return(order *models.Order, err error) *MockGophermart_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockGophermart_GetOrder_Call) RunAndReturn(run func(ctx context.Context, getOrder models.GetOrder) (*models.Order, error)) *MockGophermart_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// IndexOrder provides a mock function for the type MockGophermart
func (_mock *MockGophermart) IndexOrder(ctx context.Context, indexOrder models.IndexOrder) (<-chan models.IndexOrderResponse, <-chan error) {
	ret := _mock.Called(ctx, indexOrder)

	if len(ret) == 0 {
		panic("no return value specified for IndexOrder")
	}

	var r0 <-chan models.IndexOrderResponse
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) (<-chan models.IndexOrderResponse, <-chan error)); ok {
		return returnFunc(ctx, indexOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) <-chan models.IndexOrderResponse); ok {
		r0 = returnFunc(ctx, indexOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan models.IndexOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexOrder) <-chan error); ok {
		r1 = returnFunc(ctx, indexOrder)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// MockGophermart_IndexOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexOrder'
type MockGophermart_IndexOrder_Call struct {
	*mock.Call
}

// IndexOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - indexOrder models.IndexOrder
func (_e *MockGophermart_Expecter) IndexOrder(ctx interface{}, indexOrder interface{}) *MockGophermart_IndexOrder_Call {
	return &MockGophermart_IndexOrder_Call{Call: _e.mock.On("IndexOrder", ctx, indexOrder)}
}

func (_c *MockGophermart_IndexOrder_Call) Run(run func(ctx context.Context, indexOrder models.IndexOrder)) *MockGophermart_IndexOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexOrder
		if args[1] != nil {
			arg1 = args[1].(models.IndexOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_IndexOrder_Call) Return(indexOrderResponseCh <-chan models.IndexOrderResponse, errCh <-chan error) *MockGophermart_IndexOrder_Call {
	_c.Call.Return(indexOrderResponseCh, errCh)
	return _c
}

func (_c *MockGophermart_IndexOrder_Call) RunAndReturn(run func(ctx context.Context, indexOrder models.IndexOrder) (<-chan models.IndexOrderResponse, <-chan error)) *MockGophermart_IndexOrder_Call {
	_c.Call.Return(run)
	return _c
}

// StoreOrder provides a mock function for the type MockGophermart
func (_mock *MockGophermart) StoreOrder(ctx context.Context, storeOrder models.StoreOrder) error {
	ret := _mock.Called(ctx, storeOrder)

	if len(ret) == 0 {
		panic("no return value specified for StoreOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreOrder) error); ok {
		r0 = returnFunc(ctx, storeOrder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGophermart_StoreOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreOrder'
type MockGophermart_StoreOrder_Call struct {
	*mock.Call
}

// StoreOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - storeOrder models.StoreOrder
func (_e *MockGophermart_Expecter) StoreOrder(ctx interface{}, storeOrder interface{}) *MockGophermart_StoreOrder_Call {
	return &MockGophermart_StoreOrder_Call{Call: _e.mock.On("StoreOrder", ctx, storeOrder)}
}

func (_c *MockGophermart_StoreOrder_Call) Run(run func(ctx context.Context, storeOrder models.StoreOrder)) *MockGophermart_StoreOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreOrder
		if args[1] != nil {
			arg1 = args[1].(models.StoreOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGophermart_StoreOrder_Call) Return(err error) *MockGophermart_StoreOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGophermart_StoreOrder_Call) RunAndReturn(run func(ctx context.Context, storeOrder models.StoreOrder) error) *MockGophermart_StoreOrder_Call {
	_c.Call.Return(run)
	return _c
}
