// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alex-storchak/go-musthave-group-diploma/internal/validator"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Valid provides a mock function for the type MockValidator
func (_mock *MockValidator) Valid() validator.Problems {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 validator.Problems
	if returnFunc, ok := ret.Get(0).(func() validator.Problems); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validator.Problems)
		}
	}
	return r0
}

// MockValidator_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type MockValidator_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
func (_e *MockValidator_Expecter) Valid() *MockValidator_Valid_Call {
	return &MockValidator_Valid_Call{Call: _e.mock.On("Valid")}
}

func (_c *MockValidator_Valid_Call) Run(run func()) *MockValidator_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidator_Valid_Call) Return(problems validator.Problems) *MockValidator_Valid_Call {
	_c.Call.Return(problems)
	return _c
}

func (_c *MockValidator_Valid_Call) RunAndReturn(run func() validator.Problems) *MockValidator_Valid_Call {
	_c.Call.Return(run)
	return _c
}
