// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/go-musthave-group-diploma/internal/gophermart/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) CountOrder(ctx context.Context, indexOrder models.IndexOrder) (int64, error) {
	ret := _mock.Called(ctx, indexOrder)

	if len(ret) == 0 {
		panic("no return value specified for CountOrder")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) (int64, error)); ok {
		return returnFunc(ctx, indexOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) int64); ok {
		r0 = returnFunc(ctx, indexOrder)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexOrder) error); ok {
		r1 = returnFunc(ctx, indexOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOrder'
type MockRepository_CountOrder_Call struct {
	*mock.Call
}

// CountOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - indexOrder models.IndexOrder
func (_e *MockRepository_Expecter) CountOrder(ctx interface{}, indexOrder interface{}) *MockRepository_CountOrder_Call {
	return &MockRepository_CountOrder_Call{Call: _e.mock.On("CountOrder", ctx, indexOrder)}
}

func (_c *MockRepository_CountOrder_Call) Run(run func(ctx context.Context, indexOrder models.IndexOrder)) *MockRepository_CountOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexOrder
		if args[1] != nil {
			arg1 = args[1].(models.IndexOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountOrder_Call) Return(n int64, err error) *MockRepository_CountOrder_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountOrder_Call) RunAndReturn(run func(ctx context.Context, indexOrder models.IndexOrder) (int64, error)) *MockRepository_CountOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CountWithdrawal provides a mock function for the type MockRepository
func (_mock *MockRepository) CountWithdrawal(ctx context.Context, indexWithdrawal models.IndexWithdrawal) (int64, error) {
	ret := _mock.Called(ctx, indexWithdrawal)

	if len(ret) == 0 {
		panic("no return value specified for CountWithdrawal")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) (int64, error)); ok {
		return returnFunc(ctx, indexWithdrawal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) int64); ok {
		r0 = returnFunc(ctx, indexWithdrawal)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexWithdrawal) error); ok {
		r1 = returnFunc(ctx, indexWithdrawal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountWithdrawal'
type MockRepository_CountWithdrawal_Call struct {
	*mock.Call
}

// CountWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - indexWithdrawal models.IndexWithdrawal
func (_e *MockRepository_Expecter) CountWithdrawal(ctx interface{}, indexWithdrawal interface{}) *MockRepository_CountWithdrawal_Call {
	return &MockRepository_CountWithdrawal_Call{Call: _e.mock.On("CountWithdrawal", ctx, indexWithdrawal)}
}

func (_c *MockRepository_CountWithdrawal_Call) Run(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal)) *MockRepository_CountWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexWithdrawal
		if args[1] != nil {
			arg1 = args[1].(models.IndexWithdrawal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountWithdrawal_Call) Return(n int64, err error) *MockRepository_CountWithdrawal_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountWithdrawal_Call) RunAndReturn(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal) (int64, error)) *MockRepository_CountWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBalance(ctx context.Context, getBalance models.GetBalanceRequest) (*models.ShowBalanceResponse, error) {
	ret := _mock.Called(ctx, getBalance)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *models.ShowBalanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetBalanceRequest) (*models.ShowBalanceResponse, error)); ok {
		return returnFunc(ctx, getBalance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetBalanceRequest) *models.ShowBalanceResponse); ok {
		r0 = returnFunc(ctx, getBalance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ShowBalanceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetBalanceRequest) error); ok {
		r1 = returnFunc(ctx, getBalance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockRepository_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - getBalance models.GetBalanceRequest
func (_e *MockRepository_Expecter) GetBalance(ctx interface{}, getBalance interface{}) *MockRepository_GetBalance_Call {
	return &MockRepository_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, getBalance)}
}

func (_c *MockRepository_GetBalance_Call) Run(run func(ctx context.Context, getBalance models.GetBalanceRequest)) *MockRepository_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetBalanceRequest
		if args[1] != nil {
			arg1 = args[1].(models.GetBalanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetBalance_Call) Return(showBalanceResponse *models.ShowBalanceResponse, err error) *MockRepository_GetBalance_Call {
	_c.Call.Return(showBalanceResponse, err)
	return _c
}

func (_c *MockRepository_GetBalance_Call) RunAndReturn(run func(ctx context.Context, getBalance models.GetBalanceRequest) (*models.ShowBalanceResponse, error)) *MockRepository_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewOrders provides a mock function for the type MockRepository
func (_mock *MockRepository) GetNewOrders(ctx context.Context, numbers []string) ([]models.OrderProcess, error) {
	ret := _mock.Called(ctx, numbers)

	if len(ret) == 0 {
		panic("no return value specified for GetNewOrders")
	}

	var r0 []models.OrderProcess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]models.OrderProcess, error)); ok {
		return returnFunc(ctx, numbers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []models.OrderProcess); ok {
		r0 = returnFunc(ctx, numbers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderProcess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, numbers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetNewOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewOrders'
type MockRepository_GetNewOrders_Call struct {
	*mock.Call
}

// GetNewOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - numbers []string
func (_e *MockRepository_Expecter) GetNewOrders(ctx interface{}, numbers interface{}) *MockRepository_GetNewOrders_Call {
	return &MockRepository_GetNewOrders_Call{Call: _e.mock.On("GetNewOrders", ctx, numbers)}
}

func (_c *MockRepository_GetNewOrders_Call) Run(run func(ctx context.Context, numbers []string)) *MockRepository_GetNewOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetNewOrders_Call) Return(orderProcesss []models.OrderProcess, err error) *MockRepository_GetNewOrders_Call {
	_c.Call.Return(orderProcesss, err)
	return _c
}

func (_c *MockRepository_GetNewOrders_Call) RunAndReturn(run func(ctx context.Context, numbers []string) ([]models.OrderProcess, error)) *MockRepository_GetNewOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOrder(ctx context.Context, getOrder models.GetOrder) (*models.Order, error) {
	ret := _mock.Called(ctx, getOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetOrder) (*models.Order, error)); ok {
		return returnFunc(ctx, getOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetOrder) *models.Order); ok {
		r0 = returnFunc(ctx, getOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetOrder) error); ok {
		r1 = returnFunc(ctx, getOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - getOrder models.GetOrder
func (_e *MockRepository_Expecter) GetOrder(ctx interface{}, getOrder interface{}) *MockRepository_GetOrder_Call {
	return &MockRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, getOrder)}
}

func (_c *MockRepository_GetOrder_Call) Run(run func(ctx context.Context, getOrder models.GetOrder)) *MockRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetOrder
		if args[1] != nil {
			arg1 = args[1].(models.GetOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOrder_Call) Return(order *models.Order, err error) *MockRepository_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRepository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, getOrder models.GetOrder) (*models.Order, error)) *MockRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderUser provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOrderUser(ctx context.Context, getOrderUser models.GetOrderUser) (*models.Order, error) {
	ret := _mock.Called(ctx, getOrderUser)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderUser")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetOrderUser) (*models.Order, error)); ok {
		return returnFunc(ctx, getOrderUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetOrderUser) *models.Order); ok {
		r0 = returnFunc(ctx, getOrderUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetOrderUser) error); ok {
		r1 = returnFunc(ctx, getOrderUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOrderUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderUser'
type MockRepository_GetOrderUser_Call struct {
	*mock.Call
}

// GetOrderUser is a helper method to define mock.On call
//   - ctx context.Context
//   - getOrderUser models.GetOrderUser
func (_e *MockRepository_Expecter) GetOrderUser(ctx interface{}, getOrderUser interface{}) *MockRepository_GetOrderUser_Call {
	return &MockRepository_GetOrderUser_Call{Call: _e.mock.On("GetOrderUser", ctx, getOrderUser)}
}

func (_c *MockRepository_GetOrderUser_Call) Run(run func(ctx context.Context, getOrderUser models.GetOrderUser)) *MockRepository_GetOrderUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetOrderUser
		if args[1] != nil {
			arg1 = args[1].(models.GetOrderUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOrderUser_Call) Return(order *models.Order, err error) *MockRepository_GetOrderUser_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRepository_GetOrderUser_Call) RunAndReturn(run func(ctx context.Context, getOrderUser models.GetOrderUser) (*models.Order, error)) *MockRepository_GetOrderUser_Call {
	_c.Call.Return(run)
	return _c
}

// IndexOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) IndexOrder(ctx context.Context, indexOrder models.IndexOrder) (<-chan models.IndexOrderResponse, <-chan error) {
	ret := _mock.Called(ctx, indexOrder)

	if len(ret) == 0 {
		panic("no return value specified for IndexOrder")
	}

	var r0 <-chan models.IndexOrderResponse
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) (<-chan models.IndexOrderResponse, <-chan error)); ok {
		return returnFunc(ctx, indexOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexOrder) <-chan models.IndexOrderResponse); ok {
		r0 = returnFunc(ctx, indexOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan models.IndexOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexOrder) <-chan error); ok {
		r1 = returnFunc(ctx, indexOrder)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// MockRepository_IndexOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexOrder'
type MockRepository_IndexOrder_Call struct {
	*mock.Call
}

// IndexOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - indexOrder models.IndexOrder
func (_e *MockRepository_Expecter) IndexOrder(ctx interface{}, indexOrder interface{}) *MockRepository_IndexOrder_Call {
	return &MockRepository_IndexOrder_Call{Call: _e.mock.On("IndexOrder", ctx, indexOrder)}
}

func (_c *MockRepository_IndexOrder_Call) Run(run func(ctx context.Context, indexOrder models.IndexOrder)) *MockRepository_IndexOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexOrder
		if args[1] != nil {
			arg1 = args[1].(models.IndexOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IndexOrder_Call) Return(indexOrderResponseCh <-chan models.IndexOrderResponse, errCh <-chan error) *MockRepository_IndexOrder_Call {
	_c.Call.Return(indexOrderResponseCh, errCh)
	return _c
}

func (_c *MockRepository_IndexOrder_Call) RunAndReturn(run func(ctx context.Context, indexOrder models.IndexOrder) (<-chan models.IndexOrderResponse, <-chan error)) *MockRepository_IndexOrder_Call {
	_c.Call.Return(run)
	return _c
}

// IndexWithdrawal provides a mock function for the type MockRepository
func (_mock *MockRepository) IndexWithdrawal(ctx context.Context, indexWithdrawal models.IndexWithdrawal) ([]models.IndexWithdrawalResponse, error) {
	ret := _mock.Called(ctx, indexWithdrawal)

	if len(ret) == 0 {
		panic("no return value specified for IndexWithdrawal")
	}

	var r0 []models.IndexWithdrawalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) ([]models.IndexWithdrawalResponse, error)); ok {
		return returnFunc(ctx, indexWithdrawal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.IndexWithdrawal) []models.IndexWithdrawalResponse); ok {
		r0 = returnFunc(ctx, indexWithdrawal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IndexWithdrawalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.IndexWithdrawal) error); ok {
		r1 = returnFunc(ctx, indexWithdrawal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IndexWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexWithdrawal'
type MockRepository_IndexWithdrawal_Call struct {
	*mock.Call
}

// IndexWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - indexWithdrawal models.IndexWithdrawal
func (_e *MockRepository_Expecter) IndexWithdrawal(ctx interface{}, indexWithdrawal interface{}) *MockRepository_IndexWithdrawal_Call {
	return &MockRepository_IndexWithdrawal_Call{Call: _e.mock.On("IndexWithdrawal", ctx, indexWithdrawal)}
}

func (_c *MockRepository_IndexWithdrawal_Call) Run(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal)) *MockRepository_IndexWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.IndexWithdrawal
		if args[1] != nil {
			arg1 = args[1].(models.IndexWithdrawal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IndexWithdrawal_Call) Return(indexWithdrawalResponses []models.IndexWithdrawalResponse, err error) *MockRepository_IndexWithdrawal_Call {
	_c.Call.Return(indexWithdrawalResponses, err)
	return _c
}

func (_c *MockRepository_IndexWithdrawal_Call) RunAndReturn(run func(ctx context.Context, indexWithdrawal models.IndexWithdrawal) ([]models.IndexWithdrawalResponse, error)) *MockRepository_IndexWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockRepository
func (_mock *MockRepository) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Ping(ctx interface{}) *MockRepository_Ping_Call {
	return &MockRepository_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRepository_Ping_Call) Run(run func(ctx context.Context)) *MockRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Ping_Call) Return(err error) *MockRepository_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultBalance provides a mock function for the type MockRepository
func (_mock *MockRepository) SetDefaultBalance(ctx context.Context, setDefaultBalance models.SetDefaultBalanceRequest) error {
	ret := _mock.Called(ctx, setDefaultBalance)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.SetDefaultBalanceRequest) error); ok {
		r0 = returnFunc(ctx, setDefaultBalance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetDefaultBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultBalance'
type MockRepository_SetDefaultBalance_Call struct {
	*mock.Call
}

// SetDefaultBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - setDefaultBalance models.SetDefaultBalanceRequest
func (_e *MockRepository_Expecter) SetDefaultBalance(ctx interface{}, setDefaultBalance interface{}) *MockRepository_SetDefaultBalance_Call {
	return &MockRepository_SetDefaultBalance_Call{Call: _e.mock.On("SetDefaultBalance", ctx, setDefaultBalance)}
}

func (_c *MockRepository_SetDefaultBalance_Call) Run(run func(ctx context.Context, setDefaultBalance models.SetDefaultBalanceRequest)) *MockRepository_SetDefaultBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.SetDefaultBalanceRequest
		if args[1] != nil {
			arg1 = args[1].(models.SetDefaultBalanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SetDefaultBalance_Call) Return(err error) *MockRepository_SetDefaultBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetDefaultBalance_Call) RunAndReturn(run func(ctx context.Context, setDefaultBalance models.SetDefaultBalanceRequest) error) *MockRepository_SetDefaultBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) SetOrder(ctx context.Context, storeOrder models.StoreOrder) error {
	ret := _mock.Called(ctx, storeOrder)

	if len(ret) == 0 {
		panic("no return value specified for SetOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreOrder) error); ok {
		r0 = returnFunc(ctx, storeOrder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrder'
type MockRepository_SetOrder_Call struct {
	*mock.Call
}

// SetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - storeOrder models.StoreOrder
func (_e *MockRepository_Expecter) SetOrder(ctx interface{}, storeOrder interface{}) *MockRepository_SetOrder_Call {
	return &MockRepository_SetOrder_Call{Call: _e.mock.On("SetOrder", ctx, storeOrder)}
}

func (_c *MockRepository_SetOrder_Call) Run(run func(ctx context.Context, storeOrder models.StoreOrder)) *MockRepository_SetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreOrder
		if args[1] != nil {
			arg1 = args[1].(models.StoreOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SetOrder_Call) Return(err error) *MockRepository_SetOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetOrder_Call) RunAndReturn(run func(ctx context.Context, storeOrder models.StoreOrder) error) *MockRepository_SetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// StoreWithdrawal provides a mock function for the type MockRepository
func (_mock *MockRepository) StoreWithdrawal(ctx context.Context, storeWithdrawal models.StoreWithdrawal, setDefaultBalance models.SetDefaultBalanceRequest) error {
	ret := _mock.Called(ctx, storeWithdrawal, setDefaultBalance)

	if len(ret) == 0 {
		panic("no return value specified for StoreWithdrawal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StoreWithdrawal, models.SetDefaultBalanceRequest) error); ok {
		r0 = returnFunc(ctx, storeWithdrawal, setDefaultBalance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_StoreWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreWithdrawal'
type MockRepository_StoreWithdrawal_Call struct {
	*mock.Call
}

// StoreWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - storeWithdrawal models.StoreWithdrawal
//   - setDefaultBalance models.SetDefaultBalanceRequest
func (_e *MockRepository_Expecter) StoreWithdrawal(ctx interface{}, storeWithdrawal interface{}, setDefaultBalance interface{}) *MockRepository_StoreWithdrawal_Call {
	return &MockRepository_StoreWithdrawal_Call{Call: _e.mock.On("StoreWithdrawal", ctx, storeWithdrawal, setDefaultBalance)}
}

func (_c *MockRepository_StoreWithdrawal_Call) Run(run func(ctx context.Context, storeWithdrawal models.StoreWithdrawal, setDefaultBalance models.SetDefaultBalanceRequest)) *MockRepository_StoreWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StoreWithdrawal
		if args[1] != nil {
			arg1 = args[1].(models.StoreWithdrawal)
		}
		var arg2 models.SetDefaultBalanceRequest
		if args[2] != nil {
			arg2 = args[2].(models.SetDefaultBalanceRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_StoreWithdrawal_Call) Return(err error) *MockRepository_StoreWithdrawal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_StoreWithdrawal_Call) RunAndReturn(run func(ctx context.Context, storeWithdrawal models.StoreWithdrawal, setDefaultBalance models.SetDefaultBalanceRequest) error) *MockRepository_StoreWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderInvalid provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateOrderInvalid(ctx context.Context, accrualResponse *models.AccrualResponse) error {
	ret := _mock.Called(ctx, accrualResponse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderInvalid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.AccrualResponse) error); ok {
		r0 = returnFunc(ctx, accrualResponse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateOrderInvalid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderInvalid'
type MockRepository_UpdateOrderInvalid_Call struct {
	*mock.Call
}

// UpdateOrderInvalid is a helper method to define mock.On call
//   - ctx context.Context
//   - accrualResponse *models.AccrualResponse
func (_e *MockRepository_Expecter) UpdateOrderInvalid(ctx interface{}, accrualResponse interface{}) *MockRepository_UpdateOrderInvalid_Call {
	return &MockRepository_UpdateOrderInvalid_Call{Call: _e.mock.On("UpdateOrderInvalid", ctx, accrualResponse)}
}

func (_c *MockRepository_UpdateOrderInvalid_Call) Run(run func(ctx context.Context, accrualResponse *models.AccrualResponse)) *MockRepository_UpdateOrderInvalid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.AccrualResponse
		if args[1] != nil {
			arg1 = args[1].(*models.AccrualResponse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateOrderInvalid_Call) Return(err error) *MockRepository_UpdateOrderInvalid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateOrderInvalid_Call) RunAndReturn(run func(ctx context.Context, accrualResponse *models.AccrualResponse) error) *MockRepository_UpdateOrderInvalid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderProcessed provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateOrderProcessed(ctx context.Context, accrualResponse *models.AccrualResponse) error {
	ret := _mock.Called(ctx, accrualResponse)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.AccrualResponse) error); ok {
		r0 = returnFunc(ctx, accrualResponse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateOrderProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderProcessed'
type MockRepository_UpdateOrderProcessed_Call struct {
	*mock.Call
}

// UpdateOrderProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - accrualResponse *models.AccrualResponse
func (_e *MockRepository_Expecter) UpdateOrderProcessed(ctx interface{}, accrualResponse interface{}) *MockRepository_UpdateOrderProcessed_Call {
	return &MockRepository_UpdateOrderProcessed_Call{Call: _e.mock.On("UpdateOrderProcessed", ctx, accrualResponse)}
}

func (_c *MockRepository_UpdateOrderProcessed_Call) Run(run func(ctx context.Context, accrualResponse *models.AccrualResponse)) *MockRepository_UpdateOrderProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.AccrualResponse
		if args[1] != nil {
			arg1 = args[1].(*models.AccrualResponse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateOrderProcessed_Call) Return(err error) *MockRepository_UpdateOrderProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateOrderProcessed_Call) RunAndReturn(run func(ctx context.Context, accrualResponse *models.AccrualResponse) error) *MockRepository_UpdateOrderProcessed_Call {
	_c.Call.Return(run)
	return _c
}
